py_test(
    name = "irrigation_info_dao_test",
    srcs = ["irrigation_info_dao_test.py"],
    deps = ["//backend/dao:IrrigationInfoDAO"],
)

py_test(
    name = "zone_dao_test",
    srcs = ["zone_dao_test.py"],
    deps = ["//backend/dao:ZoneDAO"],
)

py_test(
    name = "persistent_log_dao_test",
    srcs = ["persistent_log_dao_test.py"],
    deps = ["//backend/dao:PersistentLogDAO"],
)
