py_test(
    name = "IrrigationInfoDAOTest",
    srcs = ["IrrigationInfoDAOTest.py"],
    deps = ["//backend/dao:IrrigationInfoDAO"]
)

py_test(
    name = "ZoneDAOTest",
    srcs = ["ZoneDAOTest.py"],
    deps = ["//backend/dao:ZoneDAO"]
)

py_test(
    name = "PersistentLogDAOTest",
    srcs = ["PersistentLogDAOTest.py"],
    deps = ["//backend/dao:PersistentLogDAO"]
)