py_test(
    name = "IrrigationInfoDAOTest",
    srcs = ["IrrigationInfoDAOTest.py"],
    deps = ["//backend/dao:IrrigationInfoDAO"],
)

py_test(
    name = "ZoneDAOTest",
    srcs = ["ZoneDAOTest.py"],
    deps = ["//backend/dao:ZoneDAO"],
)

py_test(
    name = "persistent_log_dao_test",
    srcs = ["persistent_log_dao_test.py"],
    deps = ["//backend/dao:PersistentLogDAO"],
)
