py_library(
    name = "log",
    srcs = ["Log.py"],
    visibility = ["//backend:__subpackages__"],
    deps = ["//backend/db:SqlLite"],
)

py_library(
    name = "authenticator",
    srcs = ["Authenticator.py"],
    visibility = ["//backend:__subpackages__"],
)
