py_library(
    name="log",
    srcs=["Log.py"],
    deps=["//backend/db:SqlLite"],
    visibility=["//backend:__subpackages__"],
)

py_library(
    name="authenticator",
    srcs=["Authenticator.py"],
    visibility=["//backend:__subpackages__"],
)
